routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layout');
});

Route::get('get/ajax/bonpot', 'App\Http\Controllers\PemilikController@getBonpot')->name('getBonpot');
// LOGIN
Route::get('login','App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login','App\Http\Controllers\AuthController@proses_login')->name('proses_login');

Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['cek_login:admin']], function () {
        Route::get('admin','App\Http\Controllers\AdminController@index')->name('admin');
        Route::get('absen','App\Http\Controllers\AdminController@show')->name('absen');
        Route::get('adminkar', 'App\Http\Controllers\KaryawanController@adminkar')->name('adminkar');

    }); 
    Route::group(['middleware' => ['cek_login:pemilik']], function () {
        Route::get('pemilik','App\Http\Controllers\PemilikController@index')->name('pemilik');
        Route::get('grafik/kinerja/{tahun}','App\Http\Controllers\PemilikController@Grafik')->name('Grafik');
        Route::get('Get_Grafik','App\Http\Controllers\PemilikController@Get_Grafik')->name('Get_Grafik');
        Route::get('bonpot','App\Http\Controllers\PemilikController@Bonpot')->name('Bonpot');
        Route::post('submit/bonpot', 'App\Http\Controllers\PemilikController@submitBonpot')->name('submitBonpot');
        Route::get('edit/{bpid}','App\Http\Controllers\PemilikController@edit')->name('edit');
        Route::any('update/{bpid}','App\Http\Controllers\PemilikController@update')->name('update');


    }); 
    Route::group(['middleware' => ['cek_login:karyawan']], function () {
        Route::get('/karyawan', 'App\Http\Controllers\KaryawanController@Dashkar')->name('karyawan');
    }); 
    Route::group(['middleware' => ['cek_login:kasir']], function () {
        Route::get('kasir','App\Http\Controllers\KasirController@index')->name('kasir');
    });   
});

Route::get('cetak/', 'App\Http\Controllers\KaryawanController@cetak')->name('cetak');
Route::resource('datakar', 'App\Http\Controllers\KaryawanController');



Route::get('print', 'App\Http\Controllers\GajiController@Print')->name('Print');

//REGISTER
Route::get('register', 'App\Http\Controllers\RegisterController@create')->name('register');
Route::post('register', 'App\Http\Controllers\RegisterController@store')->name('register');
Route::get('select2Karyawan', 'App\Http\Controllers\RegisterController@select2Karyawan')->name('select2Karyawan');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

//BAGIAN
Route::resource('bagian', 'App\Http\Controllers\BagianController');
// Route::get('bagian/{bagid}/konfirmasi',[BagianController::class], 'konfirmasi');

//  AKUN
Route::get('akun', 'App\Http\Controllers\AkunController@index')->name('akun');

//SUPPLIER
Route::resource('supplier', 'App\Http\Controllers\SupplierController');

//SUPPLYBARANG
Route::resource('supplybarang', 'App\Http\Controllers\SupplyBarangController');

//KERUSAKAN
Route::resource('kerusakan', 'App\Http\Controllers\KerusakanController');

// //MENU
Route::resource('menumakanan', 'App\Http\Controllers\MenuMakananController');

// //ABSENSI
Route::resource('absensi', 'App\Http\Controllers\AbsensiController');
Route::get('pulang/{abid}', 'App\Http\Controllers\AbsensiController@pulang')->name('pulang/');


// //GAJI
Route::resource('gaji', 'App\Http\Controllers\GajiController');
Route::get('data_table/gaji', 'App\Http\Controllers\GajiController@dataTable_gaji')->name('DTGaji');
Route::get('getKelalaian/{karnik}/{tanggal}', 'App\Http\Controllers\GajiController@getKelalaian')->name('getKelalaian');

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;
    protected $table = 'suppliers';
    protected $primaryKey = 'supkode';
    public $incrementing = false;
    protected $fillable = [
        'supkode','supnama'
    ];

}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Supplier;


class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $supplier = Supplier::latest()->paginate(5);
    
        return view('admin.supplier.index',compact('supplier'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

   
    public function create()
    {
        return view('admin.supplier.create');
    }

    
    public function store(Request $request)
    {
        $request->validate([
            'supkode' => 'required',
            'supnama' => 'required',
        ]);
    
        Supplier::create($request->all());
     
        return redirect()->route('supplier.index')
                        ->with('success','Supplier created successfully.');
    }

   
    public function show($id)
    {
        //
    }

    
    public function edit($supkode)
    {
        $supplier = Supplier::findOrFail($supkode);
        return view('admin.supplier.edit',compact('supplier'));
    }

    
    public function update(Request $request, Supplier $supplier)
    {
        $request->validate([
            'supnama' => 'required',
        ]);
    
        $supplier->update($request->all());
    
        return redirect()->route('supplier.index')
                        ->with('success','Supplier updated successfully');
    }

   
    public function destroy(Supplier $supplier)
    {
        $supplier->delete();
    
        return redirect()->route('supplier.index')
                        ->with('success','Supplier deleted successfully');
    }
}

resources/views/admin/supplier/create.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Tambah Data Supplier</h4></center>
@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
    </div>
@endif
   
<form action="{{ route('supplier.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kode Supplier:</strong>
                <input type="text" name="supkode" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Supplier:</strong>
                <input type="text" name="supnama" class="form-control" placeholder="">
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/admin/supplier/edit.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Edit Supplier</h4></center>
@endsection

@section('content')
@if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
        </div>
    @endif
  
    <form action="{{ route('supplier.update',$supplier->supkode) }}" method="POST">
        @csrf
        @method('PUT')
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kode Supplier:</strong>
                <input type="text" name="kodesup" class="form-control" placeholder=" " value="{{ $supplier->supkode }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Supplier:</strong>
                <input type="text" name="supnama" class="form-control" placeholder="" value="{{ $supplier->supnama }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
    </form>
@endsection

resources/views/admin/supplier/index.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Daftar Supplier</h4></center>
@endsection

@section('content')

<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <a class="btn btn-info btn-sm" href="{{ route('supplier.create') }}">Tambah Supplier</a>
            </div>
        </div>
    </div>

    </br>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-borderes table-striped table-hover">
        <tr>
            <th>Kode Supplier</th>
            <th>Nama Supplier</th>
            <th>AKSI</th>
        </tr>
        @foreach ($supplier as $sup)
        <tr>
            <td>{{ $sup->supkode }}</td>
            <td>{{ $sup->supnama }}</td>
            <td>
                <form action="{{ route('supplier.destroy', $sup->supkode)}}" method="post">
                <a href="{{ route('supplier.edit', $sup->supkode)}}" class="btn btn-warning btn-sm">Edit</a>
                    @csrf
                    @method('DELETE')      
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>  
@endsection