routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layout');
});

Route::get('get/ajax/bonpot', 'App\Http\Controllers\PemilikController@getBonpot')->name('getBonpot');
// LOGIN
Route::get('login','App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login','App\Http\Controllers\AuthController@proses_login')->name('proses_login');

Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['cek_login:admin']], function () {
        Route::get('admin','App\Http\Controllers\AdminController@index')->name('admin');
        Route::get('absen','App\Http\Controllers\AdminController@show')->name('absen');
        Route::get('adminkar', 'App\Http\Controllers\KaryawanController@adminkar')->name('adminkar');

    }); 
    Route::group(['middleware' => ['cek_login:pemilik']], function () {
        Route::get('pemilik','App\Http\Controllers\PemilikController@index')->name('pemilik');
        Route::get('grafik/kinerja/{tahun}','App\Http\Controllers\PemilikController@Grafik')->name('Grafik');
        Route::get('Get_Grafik','App\Http\Controllers\PemilikController@Get_Grafik')->name('Get_Grafik');
        Route::get('bonpot','App\Http\Controllers\PemilikController@Bonpot')->name('Bonpot');
        Route::post('submit/bonpot', 'App\Http\Controllers\PemilikController@submitBonpot')->name('submitBonpot');
        Route::get('edit/{bpid}','App\Http\Controllers\PemilikController@edit')->name('edit');
        Route::any('update/{bpid}','App\Http\Controllers\PemilikController@update')->name('update');


    }); 
    Route::group(['middleware' => ['cek_login:karyawan']], function () {
        Route::get('/karyawan', 'App\Http\Controllers\KaryawanController@Dashkar')->name('karyawan');
    }); 
    Route::group(['middleware' => ['cek_login:kasir']], function () {
        Route::get('kasir','App\Http\Controllers\KasirController@index')->name('kasir');
    });   
});

Route::get('cetak/', 'App\Http\Controllers\KaryawanController@cetak')->name('cetak');
Route::resource('datakar', 'App\Http\Controllers\KaryawanController');



Route::get('print', 'App\Http\Controllers\GajiController@Print')->name('Print');

//REGISTER
Route::get('register', 'App\Http\Controllers\RegisterController@create')->name('register');
Route::post('register', 'App\Http\Controllers\RegisterController@store')->name('register');
Route::get('select2Karyawan', 'App\Http\Controllers\RegisterController@select2Karyawan')->name('select2Karyawan');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

//BAGIAN
Route::resource('bagian', 'App\Http\Controllers\BagianController');
// Route::get('bagian/{bagid}/konfirmasi',[BagianController::class], 'konfirmasi');

//  AKUN
Route::get('akun', 'App\Http\Controllers\AkunController@index')->name('akun');

//SUPPLIER
Route::resource('supplier', 'App\Http\Controllers\SupplierController');

//SUPPLYBARANG
Route::resource('supplybarang', 'App\Http\Controllers\SupplyBarangController');

//KERUSAKAN
Route::resource('kerusakan', 'App\Http\Controllers\KerusakanController');

// //MENU
Route::resource('menumakanan', 'App\Http\Controllers\MenuMakananController');

// //ABSENSI
Route::resource('absensi', 'App\Http\Controllers\AbsensiController');
Route::get('pulang/{abid}', 'App\Http\Controllers\AbsensiController@pulang')->name('pulang/');


// //GAJI
Route::resource('gaji', 'App\Http\Controllers\GajiController');
Route::get('data_table/gaji', 'App\Http\Controllers\GajiController@dataTable_gaji')->name('DTGaji');
Route::get('getKelalaian/{karnik}/{tanggal}', 'App\Http\Controllers\GajiController@getKelalaian')->name('getKelalaian');

app/Models/Kerusakan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Cabang;


class Kerusakan extends Model
{
    use HasFactory;
    protected $table = 'kerusakans';
    protected $primaryKey = 'rusakid';
    public $incrementing = false;
    protected $fillable = [
        'rusakid',
        'cabkode',
        'rusaknama',
        'rusaktgl',
        'rusakjml',
        'keterangan',
        'hargapenggantian'
    ];

    public function cabang()
    {
        return $this->belongsTo(Cabang::class, 'cabkode');
    }
}

app/Http/Controllers/KerusakanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kerusakan;
use App\Models\Cabang;

class KerusakanController extends Controller
{
   
    public function index()
    {
        $kerusakan = Kerusakan::latest()->paginate(5);
    
        return view('admin.kerusakan.index',compact('kerusakan'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    
    public function create()
    {
        $cabang = Cabang::all();
        return view('admin.kerusakan.create',compact('cabang'));
    }

    
    public function store(Request $request)
    {
        $request->validate([
            'rusakid' => 'required',
            'cabkode' => 'required',
            'rusaknama' => 'required',
            'rusaktgl' => 'required',
            'rusakjml' => 'required',
            'keterangan' => 'required',
            'hargapenggantian' => 'required',
        ]);
    
        Kerusakan::create($request->all());
     
        return redirect()->route('kerusakan.index')
                        ->with('success','Data Kerusakan berhasil ditambahkan.');
    }

   
    public function show($id)
    {
        //
    }

    
    public function edit($rusakid)
    {
        $cabang = Cabang::all();
        $kerusakan = Kerusakan::findOrFail($rusakid);
        return view('admin.kerusakan.edit',compact('kerusakan','cabang'));

    }

    
    public function update(Request $request, Kerusakan $kerusakan)
    {
        $request->validate([
            'rusakid' => 'required',
            'cabkode' => 'required',
            'rusaknama' => 'required',
            'rusaktgl' => 'required',
            'rusakjml' => 'required',
            'keterangan' => 'required',
            'hargapenggantian' => 'required',
        ]);

        $kerusakan->update($request->all());

        return redirect()->route('kerusakan.index')
                        ->with('success','Data Kerusakan Berhasil diubah.');

    }

    
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/kerusakan/create.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Tambah Data Kerusakan</h4></center>
@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
    </div>
@endif
   
<form action="{{ route('kerusakan.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <strong>Kode Kerusakan</strong>
                <input type="text" name="rusakid" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-md-4">
        <div class="form-group">
            <strong>Cabang</strong>
            <select name="cabkode" id="cabang" class="form-control">
            <option value="">Pilih Cabang</option>
            @foreach ($cabang as $data)
                <option value="{{ $data -> cabkode  }}">{{ $data-> cabnama }}</option>
                @endforeach
            </select>            
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <strong>Nama Barang</strong>
                <input type="text" name="rusaknama" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <strong>Tanggal</strong>
                <input type="date" name="rusaktgl" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <strong>Jumlah</strong>
                <input type="text" name="rusakjml" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <strong>keterangan</strong>
                <input type="text" name="keterangan" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <strong>Harga</strong>
                <input type="text" name="hargapenggantian" class="form-control" placeholder="">
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/admin/kerusakan/edit.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Edit Data Barang</h4></center>
@endsection

@section('content')
@if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
        </div>
    @endif

    <form action="{{ route('kerusakan.update', $kerusakan->rusakid) }}" method="POST">
    @csrf    
    @method('PUT')

    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <strong>Kode Kerusakan</strong>
                <input type="text" name="rusakid" class="form-control" value = "{{ $kerusakan->rusakid }}">
            </div>
        </div>
        <div class="col-md-4">
        <div class="form-group">
            <strong>Cabang</strong>
            <select name="cabkode" id="cabang" class="form-control">
            <option value="">Pilih Cabang</option>
            @foreach ($cabang as $data)
                <option value="{{ $data -> cabkode  }}">{{ $data-> cabnama }}</option>
                @endforeach
            </select>            
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <strong>Nama Barang</strong>
                <input type="text" name="rusaknama" class="form-control" value = "{{ $kerusakan->rusaknama }}">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <strong>Tanggal</strong>
                <input type="date" name="rusaktgl" class="form-control" value = "{{ $kerusakan->rusaktgl }}">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <strong>Jumlah</strong>
                <input type="text" name="rusakjml" class="form-control" value = "{{ $kerusakan->rusakjml }}">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <strong>keterangan</strong>
                <input type="text" name="keterangan" class="form-control" pvalue = "{{ $kerusakan->keterangan }}">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <strong>Harga</strong>
                <input type="text" name="hargapenggantian" class="form-control" value = "{{ $kerusakan->hargapenggantian }}">
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/admin/kerusakan/index.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Daftar Kerusakan</h4></center>
@endsection

@section('content')

<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-info btn-sm" href="{{ route('kerusakan.create') }}">Tambah Data Kerusakan</a>
            </div>
        </div>
    </div>

    </br>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-borderes table-striped table-hover">
        <tr>
            <th>Kode Kerusakan</th>
            <th>Cabang</th>
            <th>Nama Barang</th>
            <th>Tanggal</th>
            <th>Jumlah</th>
            <th>keterangan</th>
            <th>Harga</th>
            <th>AKSI</th>
        </tr>
        @foreach ($kerusakan as $rusk)
        <tr>
            <td>{{ $rusk->rusakid }}</td>
            <td>{{ $rusk->cabang->cabnama }}</td>
            <td>{{ $rusk->rusaknama }}</td>
            <td>{{ $rusk->rusaktgl }}</td>
            <td>{{ $rusk->rusakjml }}</td>
            <td>{{ $rusk->keterangan }}</td>
            <td>{{ $rusk->hargapenggantian }}</td>
            <td>
                <form action="{{ route('kerusakan.destroy', $rusk->rusakid )}}" method="post">
                <a href="{{ route('kerusakan.edit', $rusk->rusakid )}}" class="btn btn-warning btn-sm">Edit</a>
                    @csrf
                    
                </form>
            </td>
        </tr>
        @endforeach
    </table>  
@endsection